### ISSUE TITLE
Allow disabling insurance

### ISSUE THREAD

**Issue by DrakiaXYZ** [DrakiaXYZ/SPT-GildedKeyStorage#2]
Most people carry these in their secure, so allow disabling insurance

**Comment by EstamNar** [comment]
Also added ability to block insurance for keys, figured if someone wanted one, theyd probably want the other as well.

**Comment by DrakiaXYZ** [comment]
Added via https://github.com/DrakiaXYZ/SPT-GildedKeyStorage/commit/2502245b4d087b2d2a7eefd665c9274768082eb7

Thanks Estam!
