### ISSUE TITLE
Terragroup Yellow Keycard - Factory Storage Room

### ISSUE THREAD

**Issue by ViP3R76** [DrakiaXYZ/SPT-GildedKeyStorage#8]
Unlocks the door to the TerraGroup storage room on Factory.

This "new" keycard does not fit in any MK or the Keycard Storage. As it belongs to factory - it should maybe put in MK.1

ID: 66acd6702b17692df20144c0
Tpl: 66acd6702b17692df20144c0 (6754537a37e940fa64004be6)

**Comment by DrakiaXYZ** [comment]
Should be fixed in 1.5.1, it's been added to the keycard holder
